apiVersion: v1
kind: Service
metadata:
  name: sample-ci-app
  namespace: cicd-lab

spec:
  type: NodePort

  selector:
    app: sample-ci-app

  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30081
